export default Object.freeze({
    FETCH_TASKS:         'FETCH_TASKS',
    FETCH_TASKS_SUCCESS: 'FETCH_TASKS_SUCCESS',
    FETCH_TASKS_FAIL:    'FETCH_TASKS_FAIL',

    DELETE_TASK:         'DELETE_TASK',
    DELETE_TASK_SUCCESS: 'DELETE_TASK_SUCCESS',
    DELETE_TASK_FAIL:    'DELETE_TASK_FAIL',

    ADD_TASK:         'ADD_TASK',
    ADD_TASK_SUCCESS: 'ADD_TASK_SUCCESS',
    ADD_TASK_FAIL:    'ADD_TASK_FAIL',

    EDIT_TASK:         'EDIT_TASK',
    EDIT_TASK_SUCCESS: 'EDIT_TASK_SUCCESS',
    EDIT_TASK_FAIL:    'EDIT_TASK_FAIL',

    CHOOSE_ALL_TASKS:         'CHOOSE_ALL_TASKS',
    CHOOSE_ALL_TASKS_SUCCESS: 'CHOOSE_ALL_TASKS_SUCCESS',
    CHOOSE_ALL_TASKS_FAIL:    'CHOOSE_ALL_TASKS_FAIL',
});
